language: java
branches:
  only:
  - master
  - develop
before_install:
- chmod +x gradlew
install: true
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-oracle-jdk6.sh
- $HOME/build-script/travis-ci/nablarch-build.sh
- $HOME/build-script/travis-ci/upload-test-report.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: 01v2dtFNALQQ6REHlNuanPs6KjH6V3upn6kIYBmJ5Pelzf9mXcddoJyBM9d7Jgy3615LmDLEiqw9DqQMIugYyw1HSbGN6m8H/prxQpv8b/1gKpS+mhEHOrMlpgf9ktab+QXwVzBqkH+wLBegasjYYoqr+R8cxtKe6rXPMux16e9/NBIoN0CYfBdGTP1qascKNcYmmOI1aFqOza+wFZUf+lllaX4YWTywHFfigLjV5YMv1mk9s/3CynOWlSCCwln1IApLVECvhMUEb02coOF1LmcphDNAr7fmlvYaZXBMmLZPwTz1UgUshJclA8XT0LsqIpapR0hYMX0a6ZG35BuAGr2xdZat7+tLmCj1fF8SMtRPUGkXpSIh/IM7OHor4naVNlSESAB1uwC8+iQXOuXu9p4O+dt/nAw8tocS9LBZnQBZgJJSfmEaDDuBi0x5LHa/htN49m+cV5qWGr2goKsxlZYHh1L4xkdBl6IaVNGKVGgeuc66SltHTeZV+VAdexduxlGoaHIhmXKV+yUIa99x2xUYZphVXjII9cgVhxzmfSf7FtUgJvDBedkQauryzkWjcikF2qE1LHvlk5IBzT5SUR0d6kOh3JU+0uLm31OamQFEKd4K0HKJjbPPYNtof043ekLZIo55sj3S+RqLqDTC+CGrCxlfFIUK3RDeSFZhdG4=
